City.create!([
  {name: "Đà Nẵng"}
])
District.create!([
  {name: "Q. Cẩm Lệ", city_id: 1},
  {name: "Q. Hải Châu", city_id: 1},
  {name: "H. Hòa Vang", city_id: 1},
  {name: "Q. Liên Chiểu", city_id: 1},
  {name: "Q. Ngũ Hành Sơn", city_id: 1},
  {name: "Q. Sơn Trà", city_id: 1},
  {name: "Q. Thanh Khê", city_id: 1}
])
Ward.create!([
  {name: "P. Hòa An", city_id: 1, district_id: 1},
  {name: "P. Hòa Thọ Đông", city_id: 1, district_id: 1},
  {name: "P. Hòa Thọ Tây", city_id: 1, district_id: 1},
  {name: "P. Hòa Xuân", city_id: 1, district_id: 1},
  {name: "P. Khuê Trung", city_id: 1, district_id: 1},
  {name: "P. Hòa Phát", city_id: 1, district_id: 1},
  {name: "P. Bình Hiên", city_id: 1, district_id: 2},
  {name: "P. Bình Thuận", city_id: 1, district_id: 2},
  {name: "P. Hải  Châu I", city_id: 1, district_id: 2},
  {name: "P. Hải Châu 2", city_id: 1, district_id: 2},
  {name: "P. Hòa Cường Bắc", city_id: 1, district_id: 2},
  {name: "P. Hòa Cường Nam", city_id: 1, district_id: 2},
  {name: "P. Bình ", city_id: 1, district_id: 2},
  {name: "P. Hòa Thuận Tây", city_id: 1, district_id: 2},
  {name: "P. Nam Dương", city_id: 1, district_id: 2},
  {name: "P. Phước Ninh", city_id: 1, district_id: 2},
  {name: "P. Thạch Thang", city_id: 1, district_id: 2},
  {name: "P. Thanh Bình", city_id: 1, district_id: 2},
  {name: "P. Thuận Phước", city_id: 1, district_id: 2},
  {name: "X. Hòa Bắc", city_id: 1, district_id: 3},
  {name: "X. Hòa Châu", city_id: 1, district_id: 3},
  {name: "X. Hòa Khương", city_id: 1, district_id: 3},
  {name: "X. Hòa Ninh", city_id: 1, district_id: 3},
  {name: "X. Hòa Phong", city_id: 1, district_id: 3},
  {name: "X. Hòa Phú", city_id: 1, district_id: 3},
  {name: "X. Hòa Phước", city_id: 1, district_id: 3},
  {name: "X. Hòa Sơn", city_id: 1, district_id: 3},
  {name: "X. Hòa Tiến", city_id: 1, district_id: 3},
  {name: "X. Hòa Liên", city_id: 1, district_id: 3},
  {name: "X. Hòa Nhơn", city_id: 1, district_id: 3},
  {name: "P. Hòa Hiệp Bắc", city_id: 1, district_id: 4},
  {name: "P. Hòa Hiệp Nam", city_id: 1, district_id: 4},
  {name: "P. Hòa Khánh Bắc", city_id: 1, district_id: 4},
  {name: "P. Hòa Khánh Nam", city_id: 1, district_id: 4},
  {name: "P. Hòa Minh", city_id: 1, district_id: 4},
  {name: "P. Liên Chiểu", city_id: 1, district_id: 4},
  {name: "P. Hòa Hải", city_id: 1, district_id: 5},
  {name: "P. Hòa Quý", city_id: 1, district_id: 5},
  {name: "P.Khuê Mỹ", city_id: 1, district_id: 5},
  {name: "P.Mỹ An", city_id: 1, district_id: 5},
  {name: "P. An Hải Bắc", city_id: 1, district_id: 6},
  {name: "P. An Hải Đông", city_id: 1, district_id: 6},
  {name: "P. An Hải Tây", city_id: 1, district_id: 6},
  {name: "P. Mân Thái", city_id: 1, district_id: 6},
  {name: "P. Nại Hiên Đông", city_id: 1, district_id: 6},
  {name: "P. Phước Mỹ", city_id: 1, district_id: 6},
  {name: "P. Thọ Quang", city_id: 1, district_id: 6},
  {name: "P. An Khê", city_id: 1, district_id: 7},
  {name: "P. Chính Gián", city_id: 1, district_id: 7},
  {name: "P. Hòa Khê", city_id: 1, district_id: 7},
  {name: "P. Tam Thuận", city_id: 1, district_id: 7},
  {name: "P. Tân Chính", city_id: 1, district_id: 7},
  {name: "P. Thạc Gián", city_id: 1, district_id: 7},
  {name: "P. Thanh Khê Đông", city_id: 1, district_id: 7},
  {name: "P. Thanh Khê Tây", city_id: 1, district_id: 7},
  {name: "P. Vĩnh Trung", city_id: 1, district_id: 7},
  {name: "P. Xuân Hà", city_id: 1, district_id: 7}
])
